name: aeroftp
version: '1.7.0'
summary: Multi-Protocol File Client - 13 Protocols, AI, Encryption (Snap = limited FS)
description: |
  AeroFTP is a cross-platform desktop client for FTP, FTPS, SFTP, WebDAV, S3,
  Google Drive, Dropbox, OneDrive, MEGA, Box, pCloud, Azure Blob, and Filen.
  13 protocols, 30 presets, one app.

  !! SNAP VERSION - LIMITED FILESYSTEM ACCESS !!
  Due to Snap strict confinement, this version can only access ~/snap/aeroftp/
  and mounted removable media. For full unrestricted access, download .deb or
  .AppImage from: https://github.com/axpnet/aeroftp/releases

  Features:
  - AeroVault: AES-256-GCM encrypted containers with Argon2id KDF
  - Cryptomator: Open and browse format 8 vaults (scrypt + AES-SIV + AES-GCM)
  - AeroAgent AI: 24 tools, 7 providers (OpenAI, Anthropic, Gemini, xAI, OpenRouter, Ollama, Custom)
  - Archive browser: Browse ZIP/7z/TAR/RAR contents in-app, selective extraction
  - Monaco code editor (VS Code engine) for remote file editing
  - Integrated terminal with SSH remote shell, 8 themes, multiple tabs
  - Dual-pane file browser with drag & drop, thumbnails, grid/list view
  - AeroCloud: Turn any FTP into a personal cloud with bidirectional sync
  - 51 languages with RTL support
  - Dark/light themes
  - In-app auto-updater

  Built with Rust (Tauri 2) + React 18 + TypeScript.
  Open source under GPL-3.0 license.

  Note: Snap filesystem limitation also affects FileZilla and other FTP clients.
  See: https://github.com/brlin-tw/filezilla-snap/issues/7

base: core22
grade: stable
confinement: strict
compression: lzo

contact: https://github.com/axpnet/aeroftp/discussions
issues: https://github.com/axpnet/aeroftp/issues
source-code: https://github.com/axpnet/aeroftp
website: https://github.com/axpnet/aeroftp
license: GPL-3.0

architectures:
  - build-on: amd64
    build-for: amd64

icon: icons/AeroFTP_simbol_color_512x512.png

apps:
  aeroftp:
    command: usr/bin/aeroftp
    desktop: usr/share/applications/aeroftp.desktop
    environment:
      # WebKitGTK environment
      GDK_BACKEND: x11
      GTK_USE_PORTAL: 1
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - unity7
      - gsettings

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    symlink: $SNAP/usr/share/xml/iso-codes

parts:
  aeroftp:
    plugin: nil
    source: .
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libgtk-3-0
      - libayatana-appindicator3-1
      - librsvg2-2
      - libssl3
      - libasound2
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - iso-codes
      - libglu1-mesa
    override-build: |
      # Copy pre-built binary
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      
      if [ -f src-tauri/target/release/aeroftp ]; then
        cp src-tauri/target/release/aeroftp $SNAPCRAFT_PART_INSTALL/usr/bin/
        chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/aeroftp
        echo "Binary copied successfully"
      else
        echo "ERROR: Binary not found at src-tauri/target/release/aeroftp"
        ls -la src-tauri/target/release/ || echo "Release directory not found"
        exit 1
      fi
      
      # Copy icon
      cp icons/AeroFTP_simbol_color_512x512.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/aeroftp.png
      
      # Create desktop entry
      cat > $SNAPCRAFT_PART_INSTALL/usr/share/applications/aeroftp.desktop << 'DESKTOP'
      [Desktop Entry]
      Name=AeroFTP
      Comment=Multi-Protocol File Client with AI & Encryption (Snap - Limited FS)
      Exec=aeroftp
      Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/aeroftp.png
      Terminal=false
      Type=Application
      Categories=Network;FileTransfer;Development;
      Keywords=ftp;sftp;file;transfer;upload;download;
      StartupWMClass=AeroFTP
      DESKTOP
      # Remove leading whitespace from desktop file
      sed -i 's/^      //' $SNAPCRAFT_PART_INSTALL/usr/share/applications/aeroftp.desktop
