name: aeroftp
version: '0.9.0'
summary: Fast, Beautiful, Reliable FTP Client built with Tauri
description: |
  AeroFTP is a modern, open-source FTP client that combines beauty and functionality.
  
  **Features:**
  - 🌍 Multi-language support (i18n) - English, Italian
  - 🚀 Fast transfers with real-time progress
  - ☁️ AeroCloud file synchronization
  - 🎨 Beautiful, modern dark/light themes
  - 📁 Dual-pane file browser (local & remote)
  - 🔄 File synchronization with conflict detection
  - 💻 Integrated DevTools (Code Editor, Terminal, AI Chat)
  - 📜 Multi-session tabs with connection caching
  - 🔐 Secure FTPS connection profiles
  - ⌨️ Keyboard shortcuts for power users
  
  Built with Rust (Tauri) and React/TypeScript for maximum performance.
  Open source under GPL-3.0 license.

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

icon: icons/AeroFTP_simbol_color_512x512.png

apps:
  aeroftp:
    command: usr/bin/aeroftp
    desktop: snap/gui/aeroftp.desktop
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - gsettings
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

parts:
  aeroftp:
    plugin: nil
    source: .
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libappindicator3-1
      - librsvg2-2
      - libayatana-appindicator3-1
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libpango-1.0-0
      - libcairo2
    override-build: |
      # Copy pre-built binary and resources
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      
      if [ -f src-tauri/target/release/aeroftp ]; then
        cp src-tauri/target/release/aeroftp $SNAPCRAFT_PART_INSTALL/usr/bin/
        chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/aeroftp
        echo "Binary copied successfully"
      else
        echo "ERROR: Binary not found at src-tauri/target/release/aeroftp"
        ls -la src-tauri/target/release/ || echo "Release directory not found"
        exit 1
      fi
      
      cp icons/AeroFTP_simbol_color_512x512.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/aeroftp.png
