name: aeroftp
version: '1.2.5'
summary: Modern FTP Client - SNAP LIMITED DEMO (Use .deb/.AppImage for full access)
description: |
  AeroFTP is a modern, open-source FTP client that combines beauty and functionality.
  
  âš ï¸  **SNAP VERSION - LIMITED DEMO** âš ï¸
  Due to Snap strict confinement restrictions (classic confinement not granted),
  this version has LIMITED filesystem access:
  - Can ONLY access: ~/snap/aeroftp/ and mounted removable media
  - CANNOT access most system directories (/home, /var, etc.)
  - Some features may not work as expected
  
  ðŸ”“ **FOR FULL UNRESTRICTED ACCESS, DOWNLOAD:**
  - .deb package (Debian/Ubuntu) - RECOMMENDED
  - .AppImage (Universal Linux) - RECOMMENDED
  - .dmg (macOS) / .msi (Windows)
  ðŸ‘‰ https://github.com/axpnet/aeroftp/releases
  
  **Features (full version):**
  ðŸŒ Multi-language (EN, IT, ES, FR, ZH)
  ðŸš€ Fast transfers with real-time progress
  â˜ï¸ AeroCloud file synchronization
  ðŸŽ¨ Beautiful dark/light themes
  ðŸ“ Dual-pane file browser
  ðŸ”„ File sync with conflict detection
  ðŸ’» DevTools (Monaco Editor, Terminal, AI Chat)
  ðŸ“œ Multi-session tabs
  ðŸ” Secure FTPS connections
  ðŸŽµ Media player & image preview
  
  Built with Rust (Tauri) + React/TypeScript.
  Open source under GPL-3.0 license.
  
  Note: This is the same limitation affecting FileZilla and other FTP clients on Snap.
  See: https://github.com/brlin-tw/filezilla-snap/issues/7

base: core22
grade: stable
confinement: strict
compression: lzo

contact: https://github.com/axpnet/aeroftp/discussions
issues: https://github.com/axpnet/aeroftp/issues
source-code: https://github.com/axpnet/aeroftp
website: https://github.com/axpnet/aeroftp
license: GPL-3.0

architectures:
  - build-on: amd64
    build-for: amd64

icon: icons/AeroFTP_simbol_color_512x512.png

apps:
  aeroftp:
    command: usr/bin/aeroftp
    desktop: usr/share/applications/aeroftp.desktop
    environment:
      # WebKitGTK environment
      GDK_BACKEND: x11
      GTK_USE_PORTAL: 1
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - unity7
      - gsettings

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    symlink: $SNAP/usr/share/xml/iso-codes

parts:
  aeroftp:
    plugin: nil
    source: .
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libgtk-3-0
      - libayatana-appindicator3-1
      - librsvg2-2
      - libssl3
      - libasound2
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - iso-codes
      - libglu1-mesa
    override-build: |
      # Copy pre-built binary
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      
      if [ -f src-tauri/target/release/aeroftp ]; then
        cp src-tauri/target/release/aeroftp $SNAPCRAFT_PART_INSTALL/usr/bin/
        chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/aeroftp
        echo "Binary copied successfully"
      else
        echo "ERROR: Binary not found at src-tauri/target/release/aeroftp"
        ls -la src-tauri/target/release/ || echo "Release directory not found"
        exit 1
      fi
      
      # Copy icon
      cp icons/AeroFTP_simbol_color_512x512.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/aeroftp.png
      
      # Create desktop entry
      cat > $SNAPCRAFT_PART_INSTALL/usr/share/applications/aeroftp.desktop << 'DESKTOP'
      [Desktop Entry]
      Name=AeroFTP
      Comment=Modern FTP Client (Snap - Limited Access)
      Exec=aeroftp
      Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/aeroftp.png
      Terminal=false
      Type=Application
      Categories=Network;FileTransfer;Development;
      Keywords=ftp;sftp;file;transfer;upload;download;
      StartupWMClass=AeroFTP
      DESKTOP
      # Remove leading whitespace from desktop file
      sed -i 's/^      //' $SNAPCRAFT_PART_INSTALL/usr/share/applications/aeroftp.desktop
