name: aeroftp
version: '0.5.6'
summary: Fast, Beautiful, Reliable FTP Client built with Tauri
description: |
  AeroFTP is a modern FTP client that combines beauty and functionality.
  
  **Features:**
  - 🚀 Fast transfers with real-time progress
  - 🎨 Beautiful, modern dark/light themes
  - 📁 Dual-pane file browser (local & remote)
  - 🔄 File synchronization with conflict detection
  - 💻 Integrated DevTools (Code Editor, Terminal, AI Chat)
  - 📜 Multi-session tabs with connection caching
  - 🔐 Secure connection profiles
  - ⌨️ Keyboard shortcuts for power users
  
  Built with Rust (Tauri) and React/TypeScript for maximum performance.

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64

icon: icons/AeroFTP_simbol_color_512x512.png

apps:
  aeroftp:
    command: usr/bin/aeroftp
    desktop: snap/gui/aeroftp.desktop
    extensions:
      - gnome
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - gsettings

parts:
  aeroftp:
    plugin: dump
    source: .
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libappindicator3-1
      - librsvg2-2
      - libayatana-appindicator3-1
    organize:
      src-tauri/target/release/aeroftp: usr/bin/aeroftp
      icons/AeroFTP_simbol_color_512x512.png: usr/share/icons/hicolor/256x256/apps/aeroftp.png
    stage:
      - usr/bin/aeroftp
      - usr/share/icons/hicolor/256x256/apps/aeroftp.png
    override-build: |
      # Copy pre-built binary
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      
      cp src-tauri/target/release/aeroftp $SNAPCRAFT_PART_INSTALL/usr/bin/ || echo "Binary not found, will be built by workflow"
      cp icons/AeroFTP_simbol_color_512x512.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/aeroftp.png

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1
